# Basic colors
COLOR_BLACK="\033[0;30m"       # Black color
COLOR_RED="\033[0;31m"         # Red color
COLOR_GREEN="\033[0;32m"       # Green color
COLOR_YELLOW="\033[0;33m"      # Yellow color
COLOR_BLUE="\033[0;34m"        # Blue color
COLOR_MAGENTA="\033[0;35m"     # Magenta color
COLOR_CYAN="\033[0;36m"        # Cyan color
COLOR_WHITE="\033[0;37m"       # White color

# Bright variants of basic colors
COLOR_BRIGHT_BLACK="\033[1;30m"   # Bright black (gray) color
COLOR_BRIGHT_RED="\033[1;31m"     # Bright red color
COLOR_BRIGHT_GREEN="\033[1;32m"   # Bright green color
COLOR_BRIGHT_YELLOW="\033[1;33m"  # Bright yellow color
COLOR_BRIGHT_BLUE="\033[1;34m"    # Bright blue color
COLOR_BRIGHT_MAGENTA="\033[1;35m" # Bright magenta color
COLOR_BRIGHT_CYAN="\033[1;36m"    # Bright cyan color
COLOR_BRIGHT_WHITE="\033[1;37m"   # Bright white color

# High-intensity color
COLOR_OCHRE="\033[38;5;95m"      # Ochre color (High intensity)

# Reset color to default
COLOR_RESET="\033[0m"            # Reset color (used to reset to default terminal color)

# Function to determine git status color
function git_color {
  local git_status="$(git status 2> /dev/null)"

  # If the working directory is clean, use red
  if [[ $git_status =~ "working directory clean" ]]; then
    echo -e $COLOR_RED
  # If the branch is ahead of remote, use yellow
  elif [[ $git_status =~ "Your branch is ahead of" ]]; then
    echo -e $COLOR_YELLOW
  # If there is nothing to commit, use green
  elif [[ $git_status =~ "nothing to commit" ]]; then
    echo -e $COLOR_GREEN
  # Otherwise, use ochre color
  else
    echo -e $COLOR_OCHRE
  fi
}

# Function to display the current git branch or commit
function git_branch {
  local git_status="$(git status 2> /dev/null)"
  local on_branch="On branch ([^${IFS}]*)"
  local on_commit="HEAD detached at ([^${IFS}]*)"

  # If on a branch, display the branch name
  if [[ $git_status =~ $on_branch ]]; then
    local branch=${BASH_REMATCH[1]}
    echo "($branch)"
  # If on a detached commit, display the commit hash
  elif [[ $git_status =~ $on_commit ]]; then
    local commit=${BASH_REMATCH[1]}
    echo "($commit)"
  fi
}

# PS1="\[\e[1;33m\][\u@\h \W]\$ \[\e[0m\]"
# Custom prompt (PS1) setup
PS1="\[$COLOR_CYAN\]\u\[$COLOR_RESET\]@\[$COLOR_GREEN\]\h\[$COLOR_RESET\]:\[$COLOR_BRIGHT_YELLOW\]\w\[$COLOR_RESET\]"  # User, host, current directory
PS1+="\[\$(git_color)\]\$(git_branch)"  # Git status color and branch name
PS1+="\[$COLOR_BLUE\]\$\[$COLOR_RESET\] "  # Blue dollar sign for prompt end
export PS1  # Apply the custom prompt

# Set locale and terminal settings
export LC_ALL=en_US.UTF-8         # Set locale to English (US)
export CLICOLOR=1                 # Enable colored output for 'ls' and other commands
export LSCOLORS=ExFxBxDxCxegedabagacad  # Custom colors for 'ls' output


[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[ -f ~/.bash_aliases ] && source ~/.bash_aliases

###
# Search up and down in the history list.
###
bind '"\C-p": previous-history'
bind '"\C-n": next-history'

# This will only work on OSX
ramdisk () {
  size_mb=$1
  sectors=$((size_mb * 2048))
  diskutil erasevolume APFS "RAMDisk" $(hdiutil attach -nomount ram://$sectors)
}

# This will only work on OSX
ramdiskeject () {
  diskutil eject /Volumes/RAMDisk
}
