#!/bin/bash

platform='unknown'

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        platform='linux'
        ~/bin/nvim-appimage $@
elif [[ "$OSTYPE" == "darwin"* ]]; then
        platform='osx'
        ~/bin/nvim-osx64/bin/nvim $@
fi
