= Installation

This is a neovim configuration mostly based on lua. There are still a couple
of vim files in transition to lua.

The plugin manager used for these files is called 'packer'.

== Get the stable neovim appimage

Check out the wonderful information at https://neovim.io/

Head over to https://github.com/neovim/neovim/wiki/Installing-Neovim and click on the
Install from download link 'Latest stable release'. That should take you to a download page for all platforms.

Scroll down to the bottom of the file and get the asset (application) that suits your platform.

For Linux:
https://github.com/neovim/neovim/releases/download/v0.6.0/nvim.appimage

For OSX:
https://github.com/neovim/neovim/releases/download/v0.6.0/nvim-macos.tar.gz

== Get the dotfiles

$ git clone https://github.com/willyclarke/dotfiles.git ~/Development/dotfiles

$ ln -s ~/Development/dotfiles/nvim/init ~/.config/nvim

== Update plugins

There is a setup.sh script associated included which may be useful for setting up neovim with this configuration.
Take a look at the content before running it. It will wipe your exisiting ~/.config/nvim config.

== Get the latest neovim

=== On linux

Go to the following page:

https://github.com/neovim/neovim/releases/nightly

=== On Osx
To install the latest, potentially unstable, development version of Neovim:

$ brew install --HEAD neovim

=== On Windows ???

