= Installing the split files nvim configuration

The 'setup.sh' file in this directory may be useful to automatically download the
nightly neovim and set up the links. The install destination in the setup.sh is
in the '~/bin directory'. It will be useful to have the '~/bin' folder in your path.

The config files in this directory has been split up into more logical parts.
There is a need for one more softlink for to set up the runtime path.

== 1. Get vundle

The init.vim relies on vundle. So prior to starting nvim you should do the following:

mkdir -p ~/.config/nvim/pack/bundle

git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/pack/bundle/Vundle.vim

== 2. Get the dotfiles

git clone https://github.com/willyclarke/dotfiles.git ~/Development/dotfiles

ln -s ~/Development/dotfiles/nvim/init/init.vim ~/.config/nvim

ln -s ~/Development/dotfiles/nvim/init ~/.nvim_runtime

== 3. Update plugins

* start nvim and do a :PluginUpdate i.e.

nvim +PluginUpdate

== 4. Additional

* Run the :checkhealth command to see what is missing on your platform. Typically there will
  be some complaints about pip3/python not installed.

* On Ubuntu the clangd daemon will act as a Language Server Protocol server. It can be installed
  with 'sudo apt install clangd'

* To get nice fonts for the status line I recommend installing the nerd fonts package. Take a look:

https://github.com/ryanoasis/vim-devicons.git
