print('hello from startup')
require('startup.packer')
require('startup.remap')
require('startup.telescope')
require('startup.colors')
require('startup.treesitter')
require('startup.fugitive')
require('startup.lsp')
require('startup.set')
