= Installing the split files nvim configuration

The config files in this directory has been split up into more logical parts.
There is a need for one more softlink for to set up the runtime path.

== Get vundle

The init.vim relies on vundle. So prior to starting nvim you should do the following:

$ mkdir -p ~/.config/nvim/pack/bundle

$ git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/pack/bundle/Vundle.vim

== Get the dotfiles

$ git clone https://github.com/willyclarke/dotfiles.git ~/Development/dotfiles

$ ln -s ~/Development/dotfiles/nvim/init/init.vim ~/.config/nvim

$ ln -s ~/Development/dotfiles/nvim/init ~/.nvim_runtime

== Update plugins

* start nvim and do a :PluginUpdate

== Additional

* Run the :checkhealth command to see what is missing on your platform. Typically there will
  be some complaints about pip3/python not installed.

* On Ubuntu the clangd daemon will act as a Language Server Protocol server. It can be installed
  with 'sudo apt install clangd'
